### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Malte-D** [Malte-D/nodemcu-servo-lightswitch#1]
- [X] add html tag to response

~~add logfile, which contains timestamps of switches~~

~~add option to view logfile in browser~~
- [ ] reduce debouncing delay
- [ ] add remote code upload functionality
